"""Added credit_score column

Revision ID: ffcc2deecdb7
Revises: 
Create Date: 2025-03-26 00:26:14.997431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffcc2deecdb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('creditscores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.drop_column('credit_score')

    op.create_table('creditscores',
    sa.Column('score_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_date', sa.DATE(), nullable=False),
    sa.Column('score_details', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='creditscores_ibfk_1'),
    sa.PrimaryKeyConstraint('score_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feedback',
    sa.Column('feedback_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_text', mysql.TEXT(), nullable=False),
    sa.Column('feedback_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='feedback_ibfk_1'),
    sa.PrimaryKeyConstraint('feedback_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
